<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsharpGalaxy.LibraryExtension" Version="2.7.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquipmentManagement.Application\EquipmentManagement.Application.csproj" />
    <ProjectReference Include="..\EquipmentManagement.IoC\EquipmentManagement.IoC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ActionFilterAttributes\" />
    <Folder Include="wwwroot\content\Landing\App_Data\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SSP1126.PcPos">
      <HintPath>..\..\..\..\Downloads\Telegram Desktop\SSP1126 - 1_4_11_2-\SSP1126 - 1.4.11.2- 1401-11-10\SSP1126 - 1.4.11.2- 1401-11-10\DLL_SSP_1.14.11.2\Release\SSP1126.PcPos.dll</HintPath>
    </Reference>
  </ItemGroup>


	
</Project>
